services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - taskflow-network

networks:
  taskflow-network:
    name: taskflow-network
    driver: bridge
