services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: taskflow-api
    restart: unless-stopped
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/taskflow
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    networks:
      - taskflow-network

  mongodb:
    image: mongo:6
    container_name: taskflow-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - taskflow-network

networks:
  taskflow-network:
    name: taskflow-network
    driver: bridge

volumes:
  mongodb-data:
    driver: local
